name: facet
channels:
  - conda-forge
dependencies:
  - aiohttp
  - geopandas
  - fsspec
  - jupyterlab
  - numpy
  - pandas
  - plotly
  - pyarrow
  - python
  - gdal=3.6.4
  - rasterio=1.3.7
  - requests
  - scipy
  - shapely
  - taudem=5.3.8
  - whitebox
