name: facet
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - fsspec
  - numpy
  - pandas
  - pyarrow
  - python=3.11
  - rasterio
  - requests
  - scipy
  - shapely
  # - taudem=5.3.8
  - whitebox
