name: facet
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp
  - geopandas
  - fsspec
  - jupyterlab
  - numpy
  - pandas
  - plotly
  - pyarrow
  - python=
  - rasterio
  - requests
  - scipy
  - shapely
  # - taudem=5.3.8
  - whitebox
