batch_csv = "c:/chesapeake_bay/sample_data/batch.csv"

[ancillary]
data = "c:/chesapeake_bay/sample_data"
flowlines = "s3://gis-data.chesapeakebay.net/public/facet_misc_data/NHDPlus_HR_NetworkFlowline.parquet"
nhd_area = "s3://gis-data.chesapeakebay.net/public/facet_misc_data/NHDPlus_HR_Area.parquet"
nhd_wbds = "s3://gis-data.chesapeakebay.net/public/facet_misc_data/NHDPlus_HR_Waterbody.parquet"
physiography = "s3://gis-data.chesapeakebay.net/public/facet_misc_data/physiography_orig.parquet"
census_roads = "s3://gis-data.chesapeakebay.net/public/facet_misc_data/Census_roads_2023.parquet"
census_rails = "s3://gis-data.chesapeakebay.net/public/facet_misc_data/Census_rails_2023.parquet"

[debug]
version = "test-01" # short description of version

[spatial_ref]
epsg = "5070"
crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"
cell_size = 1

[preprocess]
preprocess = true
    
    [preprocess.burn_stream_at_roads]
    width = 100

    [preprocess.denoise]
    filter_size = 11
    norm_diff = 10
    num_iter = 3

    [preprocess.breach_depression_least_cost]
    dist = 300 # maximum search distance for breach paths in cells
    fill = true

    [preprocess.reach-order]
    reach_id = "LINKNO"
    order_id = "strmOrder"

    [preprocess.taudem]
    cores = 2
    resample = 3

[xn_lengths]
    [xn_lengths.channel]
    "1".xn_len = 20
    "1".pf_len = 3
    "2".xn_len = 23
    "2".pf_len = 6
    "3".xn_len = 40
    "3".pf_len = 9
    "4".xn_len = 60
    "4".pf_len = 12
    "5".xn_len = 80
    "5".pf_len = 15
    "6".xn_len = 150
    "6".pf_len = 20

    [xn_lengths.floodplain]
    "1".xn_len = 50
    "1".pf_len = 5
    "2".xn_len = 75
    "2".pf_len = 8
    "3".xn_len = 100
    "3".pf_len = 12
    "4".xn_len = 150
    "4".pf_len = 20
    "5".xn_len = 200
    "5".pf_len = 30
    "6".xn_len = 500
    "6".pf_len = 40

[methods]

    [methods.cross_section]
    parm_ivert = 0.2
    parm_ratiothresh = 1.5
    parm_slpthresh = 0.03
    p_xngap = 10

    [methods.curvature]
    # note: for stream orders 5 & 6 the respective windows dimensions increase to 40x40 and 80x80
    # this is hardcoded
    win_height = 20 #rows 
    win_width = 20 #cols
    buffer = 3 # no. of cells
    curve_threshold = 0.30 # 3m DEM
    minimum_window_size = 9
    method = "wavelet"  # default
    # method = "mean"
    i_step = 100
    max_buff = 30

[postprocess]
post-process = true
stream-buffer = 60
r-exe-path = "c:/Program Files/R/.../bin/RScript.exe"
clean = false
archive = false


#####################
# old

# [file-paths]
# data_dir = "c:/chesapeake_bay/sample_data"
# ancillary-dir = "c:/chesapeake_bay/ancillary_data"
# physio-cbw = "c:/chesapeake_bay/ancillary_data/physiographic_regions_CBW.shp"
# physio-drb = "c:/chesapeake_bay/ancillary_data/physiographic_regions_DRB.shp"
# census-roads = "c:/chesapeake_bay/ancillary_data/census_roads_2018_mid_atlantic_states.shp"
# census-rails = "c:/chesapeake_bay/ancillary_data/census_rails_2018_mid_atlantic_states.shp"

# [spatial-ref]
# crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"

# [skip-HUCs]
# skip_list = ""

# [pre-process-dem]
# taudem = true
# taudem-cores = 2
# wt_grid = true
# resample-resolution = 3

# [breach-options]
# pre-condition-dem_fast-breach = true
# fast-breach = false

# [reach-and-order]
# reach_id = "LINKNO"
# order_id = "strmOrder"

# [cross-section-method]
# parm_ivert = 0.2
# parm_ratiothresh = 1.5
# parm_slpthresh = 0.03
# p_xngap = 3

# [width-from-curvature-via-buff-method]
# use_wavelet_curvature_method = true
# i_step = 100
# max_buff = 30

# [post-processing]
# post-process = true
# stream-buffer = 60
# r-exe-path = "c:/Program Files/R/.../bin/RScript.exe"
# clean = false
# archive = false



#########################