batch_csv = "c:/chesapeake_bay/sample_data/batch.csv"

[ancillary]
data = "c:/chesapeake_bay/sample_data"
flowlines = "https://gis-data.chesapeakebay.net/facet_misc_data/NHDPlus_HR_NetworkFlowline.parquet"
nhd_area = "https://gis-data.chesapeakebay.net/facet_misc_data/NHDPlus_HR_Area.parquet"
nhd_wbds = "https://gis-data.chesapeakebay.net/facet_misc_data/NHDPlus_HR_Waterbody.parquet"
physiography = "https://gis-data.chesapeakebay.net/facet_misc_data/physiography_orig.parquet"
census_roads = "https://gis-data.chesapeakebay.net/facet_misc_data/Census_roads_2023.parquet"
census_rails = "https://gis-data.chesapeakebay.net/facet_misc_data/Census_rails_2023.parquet"

[debug]
version = "test-01" # short description of version

[spatial_ref]
epsg = "5070"
crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"
cell_size = 1

[preprocess]
preprocess = true
    
    [preprocess.burn_stream_at_roads]
    width = 100

    [preprocess.denoise]
    filter_size = 11
    norm_diff = 10
    num_iter = 3

    [preprocess.breach_depression_least_cost]
    dist = 300 # maximum search distance for breach paths in cells
    fill = true

    [preprocess.reach-order]
    reach_id = "LINKNO"
    order_id = "strmOrder"

    [preprocess.taudem]
    cores = 2
    resample = 3

[xn_lengths]
    [xn_lengths.channel]
    "1".xn_len = 20
    "1".pf_len = 3
    "2".xn_len = 23
    "2".pf_len = 6
    "3".xn_len = 40
    "3".pf_len = 9
    "4".xn_len = 60
    "4".pf_len = 12
    "5".xn_len = 80
    "5".pf_len = 15
    "6".xn_len = 150
    "6".pf_len = 20

    [xn_lengths.floodplain]
    "1".xn_len = 50
    "1".pf_len = 5
    "2".xn_len = 75
    "2".pf_len = 8
    "3".xn_len = 100
    "3".pf_len = 12
    "4".xn_len = 150
    "4".pf_len = 20
    "5".xn_len = 200
    "5".pf_len = 30
    "6".xn_len = 500
    "6".pf_len = 40

[methods]

    [methods.cross_section]
    parm_ivert = 0.2
    parm_ratiothresh = 1.5
    parm_slpthresh = 0.03
    p_xngap = 10

    [methods.curvature]
    # note: for stream orders 5 & 6 the respective windows dimensions increase to 40x40 and 80x80
    # this is hardcoded
    win_height = 20 #rows 
    win_width = 20 #cols
    buffer = 3 # no. of cells
    curve_threshold = 0.30 # 3m DEM
    minimum_window_size = 9
    method = "wavelet"  # default
    # method = "mean"
    i_step = 100
    max_buff = 30

    [methods.flood_thresholds]
    # units sq kilometers
    min_drainage_area = 3
    max_drainage_area = 3000

[postprocess]
post-process = true
stream-buffer = 60
r-exe-path = "c:/Program Files/R/.../bin/RScript.exe"
clean = false
archive = false
